/*
 * say hi: the source text that the film shows, made by demo/say-hi/make_source_data.py; do not edit
 * by hand. Every comment is stripped from the lines, which keep their numbers in the file.
 */
window.SayHi = window.SayHi || {};
window.SayHi.source = Object.freeze({
  "phy": {
    "file": "characters/phy/phy.js",
    "lines": [
      {"n": 1, "text": "", "stripped": true},
      {"n": 2, "text": "", "stripped": true},
      {"n": 3, "text": "", "stripped": true},
      {"n": 4, "text": "", "stripped": true},
      {"n": 5, "text": "PhyFriends.define('phy', {", "stripped": false},
      {"n": 6, "text": "  palette: {", "stripped": false},
      {"n": 7, "text": "    bg: '#1c1d21',", "stripped": false},
      {"n": 8, "text": "    fur: '#8c7979',", "stripped": true},
      {"n": 9, "text": "    head: 'fur',", "stripped": false},
      {"n": 10, "text": "    face: '#f5ede6',", "stripped": true},
      {"n": 11, "text": "    hair: 'fur',", "stripped": false},
      {"n": 12, "text": "    ear: 'fur',", "stripped": false},
      {"n": 13, "text": "    earInner: 'almondShade',", "stripped": false},
      {"n": 14, "text": "    iris: '#9cac47',", "stripped": true},
      {"n": 15, "text": "    ink: '#2e2020',", "stripped": true},
      {"n": 16, "text": "    blush: '#fdcabc',", "stripped": false},
      {"n": 17, "text": "    tongue: 'almond',", "stripped": false},
      {"n": 18, "text": "    body: 'furShade',", "stripped": false},
      {"n": 19, "text": "    tail: '#f1e5da',", "stripped": true},
      {"n": 20, "text": "    arm: 'fur',", "stripped": false},
      {"n": 21, "text": "    paw: 'face',", "stripped": false},
      {"n": 22, "text": "    leg: 'furShade',", "stripped": false},
      {"n": 23, "text": "    foot: 'face',", "stripped": false},
      {"n": 24, "text": "    almond: '#f9bcaa',", "stripped": true},
      {"n": 25, "text": "    marble: '#d8bab0',", "stripped": true},
      {"n": 26, "text": "    chest: 'face',", "stripped": true},
      {"n": 27, "text": "    crumb: '#5f4d50',", "stripped": true},
      {"n": 28, "text": "  },", "stripped": false},
      {"n": 29, "text": "", "stripped": true},
      {"n": 30, "text": "", "stripped": true},
      {"n": 31, "text": "  head: {", "stripped": false},
      {"n": 32, "text": "    cx: 0, cy: -15.1, rx: 70, ry: 55,", "stripped": false},
      {"n": 33, "text": "    fluff: [{ from: -30, to: 10, n: 2, len: 13, lean: 4, depth: 0.1, b1: -35, b2: 10, jit: 0, sym: true }],", "stripped": false},
      {"n": 34, "text": "  },", "stripped": false},
      {"n": 35, "text": "", "stripped": true},
      {"n": 36, "text": "", "stripped": true},
      {"n": 37, "text": "  face: {", "stripped": false},
      {"n": 38, "text": "    cx: 0, cy: 24.1, rx: 64.6, ry: 18.6,", "stripped": false},
      {"n": 39, "text": "    fluff: [", "stripped": false},
      {"n": 40, "text": "      { from: 236, to: 304, n: 1, len: -3.4, b1: 0, b2: 0, jit: 0 },", "stripped": true},
      {"n": 41, "text": "      { from: -54, to: -10, n: 2, len: 3.5, depth: 0.03, b1: -40, b2: -40, jit: 0, sym: true },", "stripped": true},
      {"n": 42, "text": "      { from: -8, to: 36, n: 2, len: 3, depth: 0.04, b1: -40, b2: -40, jit: 0, sym: true },", "stripped": true},
      {"n": 43, "text": "    ],", "stripped": false},
      {"n": 44, "text": "  },", "stripped": false},
      {"n": 45, "text": "", "stripped": true},
      {"n": 46, "text": "", "stripped": true},
      {"n": 47, "text": "  ears: {", "stripped": false},
      {"n": 48, "text": "    base: [-42.5, -37], angle: 36.2, width: 65.7, length: 107, lean: 27, tip: 1, b1: -25.1, b2: -39.3,", "stripped": false},
      {"n": 49, "text": "    inner: { scale: 1, width: 39.5, length: 47.9, lean: 23.3, tip: 2.8, b1: -32.4, b2: -15.3, dx: -1.1, dy: -23.5 },", "stripped": false},
      {"n": 50, "text": "  },", "stripped": false},
      {"n": 51, "text": "", "stripped": true},
      {"n": 52, "text": "", "stripped": true},
      {"n": 53, "text": "  hair: { cx: -5, cy: -62, rx: 30, ry: 15, tips: [[-31.1, -97.4, -20.6, -37.4, [19, -69.3]], [0, -45, 0, 0, [-35.3, -60.9]]] },", "stripped": false},
      {"n": 54, "text": "", "stripped": true},
      {"n": 55, "text": "", "stripped": true},
      {"n": 56, "text": "  eyes: { x: 31, y: 0.6, w: 13, h: 33, tilt: 2, stroke: 4.5, arc: 1 },", "stripped": false},
      {"n": 57, "text": "", "stripped": true},
      {"n": 58, "text": "  blush: { x: 48.1, y: 21.3, rx: 9.6, ry: 5.5, tilt: 20 },", "stripped": false},
      {"n": 59, "text": "", "stripped": true},
      {"n": 60, "text": "  mouth: { y: 18.6, size: 3.8, fang: true },", "stripped": false},
      {"n": 61, "text": "", "stripped": true},
      {"n": 62, "text": "", "stripped": true},
      {"n": 63, "text": "  body: {", "stripped": false},
      {"n": 64, "text": "    cx: 0, cy: 80, rx: 74, ry: 51, onigiri: 1,", "stripped": false},
      {"n": 65, "text": "    fluff: [{ from: -65, to: -25, n: 2, len: 18, depth: 0, b1: 0, b2: -25, jit: 0, sym: true },", "stripped": false},
      {"n": 66, "text": "      { from: 8, to: 40, n: 2, len: 6, lean: 6, depth: 0.08, b1: -25, b2: 5, jit: 0, sym: true }],", "stripped": false},
      {"n": 67, "text": "  },", "stripped": false},
      {"n": 68, "text": "", "stripped": true},
      {"n": 69, "text": "", "stripped": true},
      {"n": 70, "text": "  tail: {", "stripped": false},
      {"n": 71, "text": "    base: [68, 85], angle: 42, length: 160, width: 108, bend: -110, taper: 0.6, root: 0.2,", "stripped": false},
      {"n": 72, "text": "", "stripped": true},
      {"n": 73, "text": "    fluff: [{ from: 240, to: 300, n: 1, len: 20, lean: -17, jit: 0, depth: 0, b1: 30, b2: -20 }],", "stripped": false},
      {"n": 74, "text": "  },", "stripped": false},
      {"n": 75, "text": "", "stripped": true},
      {"n": 76, "text": "", "stripped": true},
      {"n": 77, "text": "", "stripped": true},
      {"n": 78, "text": "", "stripped": true},
      {"n": 79, "text": "  stand: {", "stripped": false},
      {"n": 80, "text": "    seat: { paw: { cx: 22, cy: 121, rx: 14, ry: 10 }, foot: { cx: 52, cy: 116, rx: 20, ry: 15 } },", "stripped": false},
      {"n": 81, "text": "    legs: { bands: [{ from: 0.75, to: 1, color: 'face', teeth: 3, depth: 4 }] },", "stripped": false},
      {"n": 82, "text": "  },", "stripped": false},
      {"n": 83, "text": "  extras: [", "stripped": false},
      {"n": 84, "text": "", "stripped": true},
      {"n": 85, "text": "", "stripped": true},
      {"n": 86, "text": "    { feature: 'cheekRuff', on: 'base', under: true, fill: 'fur', cx: 0, cy: 19.5, rx: 81, ry: 24,", "stripped": false},
      {"n": 87, "text": "      fluff: [{ from: -40, to: 52, n: 3, len: 12, lean: 6, depth: 0.1, b1: -25, b2: 5, jit: 0, sym: true },", "stripped": false},
      {"n": 88, "text": "        { from: 53, to: 127, n: 1, len: -6.9, b1: 5, b2: 5, jit: 0 }] },", "stripped": false},
      {"n": 89, "text": "", "stripped": true},
      {"n": 90, "text": "    { feature: 'blaze', on: 'face', fill: 'face', nodes: [[0, -32.3, 1, 4], [8.2, -7.6, 1, 24], [24.7, 8.9, 1, 0], [0, 20.6, 1, 0], [-24.7, 8.9, 1, 24], [-8.2, -7.6, 1, 4]] },", "stripped": false},
      {"n": 91, "text": "", "stripped": true},
      {"n": 92, "text": "", "stripped": true},
      {"n": 93, "text": "", "stripped": true},
      {"n": 94, "text": "    { feature: 'earInner', on: 'ears', fill: 'almond', nodes: [[-11.7, -34.4, 1, -32.4], [21.5, -71.4, 1, -45], [22.8, -70.8, 1, -15.3], [20.1, -34.4, 1, 0], [4.2, -21.7]] },", "stripped": false},
      {"n": 95, "text": "", "stripped": true},
      {"n": 96, "text": "", "stripped": true},
      {"n": 97, "text": "    { feature: 'earFold', on: 'ears', clip: true, fill: 'furShade', cx: 27.7, cy: -84, rx: 43, ry: 20.9, rot: 14.8,", "stripped": false},
      {"n": 98, "text": "      fluff: [{ from: 64.6, to: 94.6, n: 1, len: 14.8, depth: 0, b1: -25, b2: 10, jit: 0 }] },", "stripped": false},
      {"n": 99, "text": "    { feature: 'earFold', on: 'ears', fill: 'furShade', nodes: [[3, -89, 1, -25], [-9, -79, 1, 15], [3, -77, 1, 0]] },", "stripped": false},
      {"n": 100, "text": "", "stripped": true},
      {"n": 101, "text": "", "stripped": true},
      {"n": 102, "text": "    { feature: 'crest', on: 'hair', clip: true, fill: 'furShade', nodes: [[-48, -72, 1], [-40, -115, 1], [25, -110, 1], [17.5, -73.8, 1, -4], [-23.1, -84.7, 1, -52], [-28.4, -60, 1]] },", "stripped": false},
      {"n": 103, "text": "    { feature: 'crest', on: 'hair', kind: 'ellipse', clip: true, fill: 'marble', cx: -49.7, cy: -94.3, rx: 36.1, ry: 8.3, rot: 47.8 },", "stripped": false},
      {"n": 104, "text": "    { feature: 'crest', on: 'hair', turn: 'forward', fill: 'marble', nodes: [[-37, -63, 1, 40], [-53, -42, 1, 0], [-39, -40, 1, -40]] },", "stripped": false},
      {"n": 105, "text": "", "stripped": true},
      {"n": 106, "text": "", "stripped": true},
      {"n": 107, "text": "", "stripped": true},
      {"n": 108, "text": "    { feature: 'chest', on: 'scarf', fill: 'marble', cx: 0, cy: 68, rx: 48.5, ry: 38, onigiri: 1,", "stripped": false},
      {"n": 109, "text": "      fluff: [{ from: -25, to: 29, n: 1, len: 9, depth: 0.04, b1: -40, b2: -40, jit: 0, sym: true },", "stripped": false},
      {"n": 110, "text": "        { from: 30, to: 150, n: 4, len: 9, depth: 0.04, b1: -40, b2: -40, jit: 0 }] },", "stripped": false},
      {"n": 111, "text": "    { feature: 'chest', on: 'scarf', fill: 'chest', cx: 0, cy: 68, rx: 44, ry: 34, onigiri: 1,", "stripped": false},
      {"n": 112, "text": "      fluff: [{ from: -60, to: 48, n: 3, len: 10, depth: 0.04, b1: -40, b2: -40, jit: 0, sym: true },", "stripped": false},
      {"n": 113, "text": "        { from: 49, to: 131, n: 3, len: 10, depth: 0.04, b1: -40, b2: -40, jit: 0 },", "stripped": false},
      {"n": 114, "text": "        { from: 241, to: 299, n: 3, len: 8, depth: 0.04, b1: -40, b2: -40, jit: 0 }] },", "stripped": false},
      {"n": 115, "text": "", "stripped": true},
      {"n": 116, "text": "    { feature: 'crumbs', on: 'scarf', fill: 'crumb', polys: [[-16, 66, 11, 6, 10], [-25, 96, 8, 4, 60, 0.7], [-8, 90, 6, 3, 20], [10, 64, 6.5],", "stripped": false},
      {"n": 117, "text": "      [-1, 64, 3.5, 4, 80, 0.7], [8.5, 46, 4.5, 4, 30, 0.7]] },", "stripped": false},
      {"n": 118, "text": "", "stripped": true},
      {"n": 119, "text": "", "stripped": true},
      {"n": 120, "text": "", "stripped": true},
      {"n": 121, "text": "    { feature: 'tailTip', on: 'tail', clip: true, fill: 'chest', cx: 0, cy: -168, rx: 108, ry: 24,", "stripped": false},
      {"n": 122, "text": "      fluff: [{ from: 60, to: 120, n: 3, len: 5.5, jit: 0, depth: 0.04 }] },", "stripped": false},
      {"n": 123, "text": "", "stripped": true},
      {"n": 124, "text": "    { feature: 'marbling', on: 'tail', clip: true, fill: 'marble', cx: 28, cy: -104, rx: 37.4, ry: 34, rot: 10 },", "stripped": false},
      {"n": 125, "text": "    { feature: 'marbling', on: 'tail', clip: true, fill: 'marble', cx: -25, cy: -95, rx: 24.1, ry: 21, rot: 20 },", "stripped": false},
      {"n": 126, "text": "", "stripped": true},
      {"n": 127, "text": "    { feature: 'tailBase', on: 'tail', clip: true, fill: 'crumb', cx: 0, cy: 0, rx: 72, ry: 80, rot: -5,", "stripped": false},
      {"n": 128, "text": "      fluff: [{ from: 222, to: 262, n: 3, len: 0.8, lean: 5, depth: 0.07, b1: -15, b2: 0, jit: 0 },", "stripped": false},
      {"n": 129, "text": "        { from: 263, to: 318, n: 3, len: 1.6, lean: 7, depth: 0.1, b1: -15, b2: 0, jit: 0 }] },", "stripped": false},
      {"n": 130, "text": "", "stripped": true},
      {"n": 131, "text": "    { feature: 'crumbs', on: 'tail', clip: true, fill: 'crumb', polys: [[45, -100, 11, 6, 15], [-10, -95, 5, 5, 10], [48, -78, 4, 4, 30, 0.7], [-6, -142, 5, 3, 0]] },", "stripped": false},
      {"n": 132, "text": "    { feature: 'crumbs', on: 'tail', clip: true, fill: 'tail', polys: [[25, -70, 5, 3, 10]] },", "stripped": false},
      {"n": 133, "text": "", "stripped": true},
      {"n": 134, "text": "", "stripped": true},
      {"n": 135, "text": "    { feature: 'crumbs', on: 'pawL', fill: 'crumb', polys: [[-2, 0, 4, 3, 30]] },", "stripped": false},
      {"n": 136, "text": "    { feature: 'crumbs', on: 'pawR', fill: 'crumb', polys: [[5, -3, 3.5, 4, 110, 0.7]] },", "stripped": false},
      {"n": 137, "text": "  ],", "stripped": false},
      {"n": 138, "text": "", "stripped": true},
      {"n": 139, "text": "  rig: { ground: 131 },", "stripped": false},
      {"n": 148, "text": "});", "stripped": false}
    ]
  },
  "onigiri": {"file": "src/phyfriends.js", "n": 157, "text": "const ONIGIRI = { square: 0, taper: 0.8 };"},
  "tests": {
    "passed": 158,
    "failed": 0,
    "summary": "158 passed, 0 failed",
    "names": [
      {"name": "every friend but Claude keeps to the house anatomy", "ok": true},
      {"name": "Claude is the one friend outside the house anatomy", "ok": true},
      {"name": "every friend's palette opens with the same roles, in the same order", "ok": true},
      {"name": "a friend that stands and leaves out its seated foot departs from the anatomy", "ok": true},
      {"name": "a turn number that the house lacks, or an extra that turns with no group of the house, departs from the anatomy", "ok": true},
      {"name": "a part left out, a misnamed key, and a part with a color of its own each depart from the anatomy", "ok": true},
      {"name": "an extra names a feature of the house list, so that what friends share has one name", "ok": true},
      {"name": "a palette role may name another role, or its house shade, and takes its color", "ok": true},
      {"name": "every friend of the house has the parts that a pose moves, under the same names", "ok": true},
      {"name": "every friend of the house can stand and show its feelings", "ok": true},
      {"name": "every movement and every feeling poses every friend in finite numbers, sitting and standing", "ok": true},
      {"name": "every friend of the house draws every feeling, standing, in finite numbers", "ok": true},
      {"name": "a mounted rig draws every pose of every friend as a fresh render of that pose draws it", "ok": true},
      {"name": "every friend of the house turns to each quarter, sitting and standing, in finite numbers, and keeps its parts", "ok": true},
      {"name": "every friend of the house, side-on, has its face ahead of the middle of its head with its near eye alone, and from behind, none", "ok": true},
      {"name": "every friend of the house sits and stands on its ground", "ok": true},
      {"name": "every friend of the house sits and stands on its ground in every quarter turn", "ok": true},
      {"name": "every friend of the house sits and stands on its ground with a taller or a shorter body", "ok": true},
      {"name": "every friend of the house keeps a foot on the ground as it walks, facing the viewer or side-on", "ok": true},
      {"name": "every limb of every friend of the house shows against what lies behind it, sitting and standing", "ok": true},
      {"name": "a paw raised in front of the face shows against it, even where it is the color of the face, in its house shade", "ok": true},
      {"name": "every friend of the house waves and points with the arm away from its tail", "ok": true},
      {"name": "every friend of the house turns its ears out on a positive rotation, about their roots, but for a flap hung from its fold", "ok": true},
      {"name": "a clip is a deterministic function of time", "ok": true},
      {"name": "a looping clip repeats every duration", "ok": true},
      {"name": "a one-shot clip holds its end pose after it ends and its first pose before it starts", "ok": true},
      {"name": "layer loops over the common period of its looping clips", "ok": true},
      {"name": "seq plays clips one after another, and a number is a rest", "ok": true},
      {"name": "sample clamps the gaze, the turn and the blink, and keeps the blush positive", "ok": true},
      {"name": "frames leaves out the last frame of a loop, which would repeat the first", "ok": true},
      {"name": "parse accepts a clip name or an expression", "ok": true},
      {"name": "in an expression, a clip's name called with options makes that clip, as make does", "ok": true},
      {"name": "parse makes every clip and feeling of an expression for the friend given", "ok": true},
      {"name": "extend adds names to what parse understands, but never replaces one", "ok": true},
      {"name": "a stack fades its layers in and out and plays each from its own start", "ok": true},
      {"name": "under reduced motion a stack passes on only the face: eye and mouth shapes, lids and blush", "ok": true},
      {"name": "lid, lidTilt and flush are clamped like the other ranged fields", "ok": true},
      {"name": "an unknown ease is an error", "ok": true},
      {"name": "a friend turns round a quarter at a time, and a mirror turns it the other way", "ok": true},
      {"name": "the standing movements start and end at rest, or loop in a length that divides 8 s", "ok": true},
      {"name": "no movement lifts a foot by less than nothing, and sample keeps the figure within what it can take", "ok": true},
      {"name": "idle breathes with a standing friend's arms, a little", "ok": true},
      {"name": "standUp and sitDown raise and lower the head smoothly", "ok": true},
      {"name": "walking steps off with the foot on the side it goes to and keeps a planted foot where it was", "ok": true},
      {"name": "a mirrored clip turns the other way and swaps every pair, limbs too, but keeps the tail on its side", "ok": true},
      {"name": "under reduced motion a standing friend keeps its stance, and drops the arm movements and over, which are not the face", "ok": true},
      {"name": "two friends are strangers unless the cast says they know each other", "ok": true},
      {"name": "the host knows everyone", "ok": true},
      {"name": "strangers may share a scene, look at and greet each other", "ok": true},
      {"name": "strangers may not stand close, talk, give or team up", "ok": true},
      {"name": "touch and rivalry need an opt-in even between friends who know each other", "ok": true},
      {"name": "a refusal names both friends as their owners write them and says how to allow it", "ok": true},
      {"name": "only a friend with a voice says words; everyone may use marks", "ok": true},
      {"name": "strangers keep a wider gap than friends who know each other, and touch removes it", "ok": true},
      {"name": "a medium counts only once the owner has agreed to it", "ok": true},
      {"name": "a cast naming an unknown friend or opt-in is refused", "ok": true},
      {"name": "the installed cast credits every registered friend", "ok": true},
      {"name": "an opt-in pair named twice keeps the verbs of both entries", "ok": true},
      {"name": "every friend but Claude fits the emotion library", "ok": true},
      {"name": "for a friend that shows no feelings, a feeling is its movement alone", "ok": true},
      {"name": "a friend that shows no feelings still smiles when greeted, without the blush or posture of joy", "ok": true},
      {"name": "a feeling that is not in the library is an error that lists the ones that are", "ok": true},
      {"name": "every face is a pose the renderer draws on every friend of the house template", "ok": true},
      {"name": "a reaction ends in the face the feeling holds, and feel carries on from there", "ok": true},
      {"name": "a held feeling loops in a length that divides 8 s, so that it loops with idle", "ok": true},
      {"name": "feel plays the reaction, then the feeling held, for ever", "ok": true},
      {"name": "strength scales the movement and keeps the face from half strength up", "ok": true},
      {"name": "feelings near each other on the two axes share their posture", "ok": true},
      {"name": "a standing friend's posture carries its arms: up when pleased or alert, in when low, limp when drowsy", "ok": true},
      {"name": "every face is a pose the renderer draws on every friend of the house template standing", "ok": true},
      {"name": "a gesture that raises a paw above the chin draws that arm whole in front (over), so that its shoulder does not hide the paw", "ok": true},
      {"name": "every mark a feeling shows is one a friend without a voice may use", "ok": true},
      {"name": "a mark pops up, fades out at its end, and keeps still under reduced motion", "ok": true},
      {"name": "describe says what a screen reader hears, with the name as its owner writes it", "ok": true},
      {"name": "the lids come down over the open eyes, and flush spreads the blush", "ok": true},
      {"name": "the dizzy eyes swirl the other way in each eye, and the flat and wobbly mouths show when posed", "ok": true},
      {"name": "every mark is written in the hand or drawn, and a drawn one is a pencil line an em tall, never filled", "ok": true},
      {"name": "a stroke is two turns of the pointer within a moment, each after a few pixels", "ok": true},
      {"name": "the friends doze off one at a time, in a seeded order, each falling asleep a few seconds later", "ok": true},
      {"name": "what a screen reader hears when the friends doze and wake", "ok": true},
      {"name": "a hi hops twice, a friend in the air ignores another, and the third hi of a run makes it shy for a while", "ok": true},
      {"name": "a friend added standing stays standing through a hi, and under reduced motion too", "ok": true},
      {"name": "a friend that shows no feelings hops and smiles on a hi, never goes shy, and its third hi plays its routine", "ok": true},
      {"name": "under reduced motion the routine is its face alone: Claude winks, and its laptop stays away", "ok": true},
      {"name": "under reduced motion a hi is a smile, and nothing moves", "ok": true},
      {"name": "stroking a friend makes it content until a moment after the stroking stops", "ok": true},
      {"name": "the stage tells the page how long a friend has been stroked, until the stroking stops", "ok": true},
      {"name": "the left and right arrow keys, pressed in turn, stroke a friend too", "ok": true},
      {"name": "a finger held still on a friend strokes it, and the tap that ends the press is not a hi", "ok": true},
      {"name": "a friend hovered for a moment grows curious until the pointer leaves", "ok": true},
      {"name": "with no pointer, the others look at the friend the keyboard is on", "ok": true},
      {"name": "left alone, everyone but Claude dozes off, and any input wakes them with a start", "ok": true},
      {"name": "falling asleep is told once a visit, and waking is not told when the reader only moves about the page", "ok": true},
      {"name": "the hold and feel options hold a greeting or a feeling still, for screenshots", "ok": true},
      {"name": "keep still: a checkbox makes the choice, which is remembered, or else the system decides", "ok": true},
      {"name": "a friend added standing shows its marks higher by its lift", "ok": true},
      {"name": "the pen pauses between strokes, longer between letters and longest between words", "ok": true},
      {"name": "a stroke is written slowly at each end and fully by its end", "ok": true},
      {"name": "the text shows as far as the pen has written it", "ok": true},
      {"name": "a pen that does not fit the text is refused", "ok": true},
      {"name": "the pencil bitmap has the grain of the texture it stands in for, in every variant", "ok": true},
      {"name": "a rig shows the variant of the texture it is set to", "ok": true},
      {"name": "the pencil masks one isolated group, for a character and for a prop", "ok": true},
      {"name": "an extra with a show name is drawn only while the pose shows that name", "ok": true},
      {"name": "an extra on the ground stays put while the friend hops, squashes or moves", "ok": true},
      {"name": "a friend sits and stands in its seated body, on the same limbs, with nothing swapped", "ok": true},
      {"name": "the limbs and the ground are fitted to the friend's body", "ok": true},
      {"name": "a taller body grows down from under the chin, and what rests on the ground drops with its base", "ok": true},
      {"name": "an onigiri body is a rice ball: narrower at the top by its taper, squared off at the base by its square, with its tufts kept", "ok": true},
      {"name": "a friend with stand: false, or without a body, keeps its seated figure in any stance", "ok": true},
      {"name": "a standing friend's feet rest on the ground where its seated paws do", "ok": true},
      {"name": "its feet stay planted while it crouches and leans, and a step lifts that foot alone", "ok": true},
      {"name": "an arm raises outward in front of the head, and in its own layer while over names it", "ok": true},
      {"name": "a friend is one figure, whose stance is any height between sitting and standing", "ok": true},
      {"name": "as it sits, its limbs fold: feet out beside its base, paws in front, and nothing jumps", "ok": true},
      {"name": "seated, its arms hang straight down in front of its body to its paws, from the body's middle, sleeves and all", "ok": true},
      {"name": "seated, its paws and feet are its seated drawing's; standing, the template's", "ok": true},
      {"name": "its feet lie in front of its body, and a crouch drops its paws with the body, by the crouch and no more", "ok": true},
      {"name": "the body and its clothes, the scarf, the head, then the arms, whose shoulders tuck under the scarf and head", "ok": true},
      {"name": "a spec may fit the template to itself", "ok": true},
      {"name": "a limb's arc keeps its length however it bends, and bendFor inverts it", "ok": true},
      {"name": "seated, a friend ignores the arm, leg, lean and crouch fields", "ok": true},
      {"name": "a tail with a standing place of its own moves there as the friend rises, from where it sits", "ok": true},
      {"name": "a paw raised to the face shows in front of the head, while the shoulder tucks under it unless over names the arm", "ok": true},
      {"name": "a plush leg squashes to take up a crouch, where a leg with knees bows out, and either stretches a little first", "ok": true},
      {"name": "a friend turns a quarter at a time, and one that never stands never turns", "ok": true},
      {"name": "from behind, a friend is its own mirror image, its face hidden, its arms beside it and its tail over it", "ok": true},
      {"name": "side-on, the far arm hangs behind the body, the far leg comes first, the near eye alone shows, and the face, the eye and the chest go ahead", "ok": true},
      {"name": "side-on, the hair bends from the head to the face, a dotted mark loses its far dots, glasses are left out, the far ear shows its back, the near eye lies over the hair, and the face keeps its patch", "ok": true},
      {"name": "side-on, a friend is drawn from the shared numbers: its body as wide as TURN.body has it, whatever its figure", "ok": true},
      {"name": "a mounted rig that turns draws itself afresh in the same svg, and keeps its parts and its texture", "ok": true},
      {"name": "writing with a pen that does not fit the text falls back to writing from left to right", "ok": true},
      {"name": "a frame depends only on the time: seeking back redraws it exactly", "ok": true},
      {"name": "a friend stands up and sits down on cue, walking while it stands and hopping while it sits", "ok": true},
      {"name": "a friend added standing has its eyes raised by its lift", "ok": true},
      {"name": "a friend raises its eyes smoothly as it stands up, and lowers them as it sits", "ok": true},
      {"name": "a friend that never stands ignores a cue to stand, and hops even when added standing", "ok": true},
      {"name": "a change of stance cued while another is under way follows it, and one to the stance cued does nothing", "ok": true},
      {"name": "a friend who enters is hidden before its entrance and ends on its mark", "ok": true},
      {"name": "a feeling shows its face and its mark, and a mark that repeats does so while it is held", "ok": true},
      {"name": "a friend that shows no feelings makes their movements without their faces, but smiles when it greets", "ok": true},
      {"name": "strangers who stand too close break the scene", "ok": true},
      {"name": "strangers may stand a polite distance apart", "ok": true},
      {"name": "the host may stand closer to a friend than strangers may", "ok": true},
      {"name": "a friend without a voice may not say words, and strangers may not talk or hand things over", "ok": true},
      {"name": "the host may talk to anyone and hand them things", "ok": true},
      {"name": "the draft stamp shows while a friend on stage has not agreed to the medium", "ok": true},
      {"name": "a filmable scene lists the friends whose owners have not agreed to video", "ok": true},
      {"name": "the credit line names the owners of the friends in frame, in order of appearance", "ok": true},
      {"name": "a boiling scene redraws the pencil texture as a function of time", "ok": true},
      {"name": "the film contract reads consent when filmed, not when the film was declared", "ok": true},
      {"name": "a friend may enter, exit and enter again, and a later move does not bring it back", "ok": true},
      {"name": "a friend refused for standing too close leaves the scene as it was", "ok": true},
      {"name": "removing a prop twice leaves the other props drawn", "ok": true},
      {"name": "a move cued in the middle of a leap waits for the landing", "ok": true},
      {"name": "a friend may look at a prop", "ok": true},
      {"name": "the gallery's labels agree with the cast", "ok": true},
      {"name": "the pages load every friend of the cast, in its order, and the gallery's rows fit the friends' reaches", "ok": true}
    ],
    "leftOut": 0,
    "ran": "2026-10-04"
  }
});
